spring:
  profiles:
    active: before_route
#  cloud:
#    gateway:
#      routes:
#        - id: before_route
#          uri: http://localhost:7771
#          predicates:
#            - After=2022-01-20T17:42:47.789-07:00[America/Denver]
#            - Before=2023-01-20T17:42:47.789-07:00[America/Denver]
#            - Between=2021-01-20T17:42:47.789-07:00[America/Denver], 2023-01-21T17:42:47.789-07:00[America/Denver]
#            - Cookie=chocolate, ch.p
#            - Header=X-Request-Id, \d+
#            - Host=**.somehost.org,**.anotherhost.org
#            - Method=GET,POST
#            - Path=/red/{segment},/blue/{segment}
#            - Query=green
#            - Query=red, gree.
#            - RemoteAddr=192.168.1.1/24
#            - XForwardedRemoteAddr=192.168.1.1/24
#          filters:
#            - AddRequestHeader=X-Request-red, blue
#            - AddRequestHeader=X-Request-Red, Blue-{segment}
#            - AddRequestParameter=red, blue
#            - AddRequestParameter=foo, bar-{segment}
#            - AddResponseHeader=X-Response-Red, Blue
#            - AddResponseHeader=foo, bar-{segment}
#            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#            - CircuitBreaker=myCircuitBreaker
#            - name: CircuitBreaker
#              args:
#                name: myCircuitBreaker
#                fallbackUri: forward:/inCaseOfFailureUseThis
#            - RewritePath=/consumingServiceEndpoint, /backingServiceEndpoint




